name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ x86_64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar python3 python3-pip python3-venv
          case "${{ matrix.arch }}" in
            x86_64)
              sudo apt-get install -y gcc g++
              ;;
          esac

      - name: Download Python source code
        run: |
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
          tar xzf Python-3.13.0.tgz
          mv Python-3.13.0 python-src

      - name: Build libpython3.x.a and install dependencies
        run: |
          cd python-src
          mkdir -p build
          case "${{ matrix.arch }}" in
            x86_64)
              ./configure --build=x86_64-linux-gnu --host=x86_64-linux-gnu --enable-optimizations --enable-ipv6 --enable-shared --enable-static --prefix=$(pwd)/build/x86_64
              ;;
          esac
          make -j$(nproc)
          make install

          # Add Python bin to PATH and install dependencies
          export PATH=$(pwd)/build/${{ matrix.arch }}/bin:$PATH
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install markitdown

      - name: Save built libraries
        run: |
          mkdir -p libs/${{ matrix.arch }}
          cp -r python-src/build/${{ matrix.arch }}/lib/* libs/${{ matrix.arch }}
          cp -r python-src/build/${{ matrix.arch }}/include libs/${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          name: libpython-${{ matrix.arch }}
          path: libs/${{ matrix.arch }}
