name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, x86, arm64, arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar \
            gcc-multilib g++-multilib \
            gcc-arm-linux-gnueabi g++-arm-linux-gnueabi \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            python3 python3-pip python3-venv

      - name: Download Python source code
        run: |
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
          tar xzf Python-3.13.0.tgz
          mv Python-3.13.0 python-src

      - name: Build libpython3.x.a and install dependencies
        run: |
          cd python-src
          mkdir build
          case "${{ matrix.arch }}" in
            x86_64)
              ./configure --enable-optimizations --disable-shared --host=x86_64-linux-gnu --prefix=$(pwd)/build/x86_64
              ;;
            x86)
              ./configure --enable-optimizations --disable-shared --host=i686-linux-gnu --prefix=$(pwd)/build/x86
              ;;
            arm64)
              ./configure --enable-optimizations --disable-shared --host=aarch64-linux-gnu --prefix=$(pwd)/build/arm64
              ;;
            arm)
              ./configure --enable-optimizations --disable-shared --host=arm-linux-gnueabi --prefix=$(pwd)/build/arm
              ;;
          esac
          make -j$(nproc)
          make install

          export PATH=$(pwd)/build/${{ matrix.arch }}/bin:$PATH
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install markitdown

      - name: Save built libraries
        run: |
          mkdir -p libs/${{ matrix.arch }}
          cp -r python-src/build/${{ matrix.arch }}/lib/* libs/${{ matrix.arch }}
          cp -r python-src/build/${{ matrix.arch }}/include libs/${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          name: libpython-${{ matrix.arch }}
          path: libs/${{ matrix.arch }}
